version: '2.1'
services:
  minecraft:
    # http://minecraft.gamepedia.com/Server/Requirements/Dedicated#Console
    mem_limit: 1g
    image: felix/minecraft:1.12
    volumes:
      - ./data:/home/minecraft
    ports:
      - 25565:25565
